BuildNetboot: Cope with Edk2/UefiPayloadPkg/NetBoot not existing yet
Use os.makedirs to create intermediate directories too since the
Edk2/UefiPayloadPkg/NetBoot directory doesn't exist either. This fixes
the following build error:

 Traceback (most recent call last):
   File "/overflow/mac/nobackup/git/netboot/./BuildNetboot.py", line 138, in <module>
     main()
   File "/overflow/mac/nobackup/git/netboot/./BuildNetboot.py", line 135, in main
     args.func(args)
   File "/overflow/mac/nobackup/git/netboot/./BuildNetboot.py", line 109, in cmd_build_dsc
     os.mkdir (os.path.dirname(netboot_path))
 FileNotFoundError: [Errno 2] No such file or directory: 'UefiPayloadPkg/NetBoot/X64'